version: "3.8"

services:
  flask:
    image: tic-tac-qu-flask
    volumes:
    - flask-data:/app
    ports:
    - 5000:5000
    environment:
      FLASK_ENV: "development"
      FLAK_APP: "webinterface"
    links:
      - "db:pgsql-server"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:5
    environment:
      PGADMIN_DEFAULT_EMAIL: simon@simonschmidt.xyz
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    links:
      - "db:pgsql-server"

volumes:
  flask-data:
  db-data:
  pgadmin-data:
