version: "3.8"

services:
  flask:
    image: tic-tac-qu-flask-test
    ports:
    - 5000:5000
    depends_on:
      - db
    links:
      # network connection with these services
      - db

  db:
    image: tic-tac-qu-postgres
    ports:
      - "5432:5432"