version: "3.8"

services:
  flask:
    image: tic-tac-qu-flask-test
    ports:
    - 5000:5000
    environment:
      FLASK_ENV: "development"
    links:
      - "db:pgsql-server"
    depends_on:
      - db
  db:
    image: tic-tac-qu-postgres
    ports:
      - "5432:5432"
