version: "3.8"

services:
  flask:
    image: tic-tac-qu-flask-system
    ports:
    - 5000:5000
    links:
      - "db:pgsql-server"
    depends_on:
      - db

  db:
    image: tic-tac-qu-postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adminstuff.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    links:
      - "db:pgsql-server"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge